name: "hello word2"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
   hellow-word:
     runs-on: "ubuntu-latest"

     steps:
      -  uses: actions/checkout@v4
         with: 
           tag: tag/1.0.1
      -  uses: ./
  
     
