name: "hello word2"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
   hellow-word:
     runs-on: "ubuntu-latest"

     steps:
     - uses: ipassynk/egghead-code-examples@v1.0.1
     - uses: ./
  
     
